### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [K-Takano41/memory_update_app#55]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
挙動の確認を行い、概ねREADMEに記載されていることを扱えるのを確認しました。LGTMです。

## 静的コードチェックが入っている
・Rubocopを通しましょう。いくつか指摘を受けるかと思うので修正しましょう。

## 就活において十分な技術力を示せる機能を実装しているか
・画像加工の技術は良いと思いました。
・結論から申しますと、やや十分な技術力を示せすのには達していないと感じました。
・以下の機能を実装できないか検討しましょう。

```
◯ステップ入力・確認画面
概要：1つのフォームで入力するには項目が多すぎる場合や、ユーザーの離脱を抑制するために、フォームを複数のステップに分割して入力できるようにすることがあります。また、1つのフォームで入力する場合でも、投稿後に編集できない情報がある場合には、確認画面を挟むことでユーザーに注意を促すなど、登録フォームのユーザビリティを考慮した様々な工夫が必要です。

◯キューとバックグラウンド処理
概要：バックグラウンド処理を利用することで、ユーザーが操作した処理に対して、その場ですぐに処理が完了するのではなく、キューに貯めておいてバックグラウンドで処理することができます。このようにすることで、ユーザーが待ち時間を減らし、スムーズな利用体験を提供することができます。特に、Web APIへの問い合わせや長時間かかる処理などはバックグラウンドに処理をまわすことがおすすめです。
使用技術・ライブラリ：
- ActiveJob（Rails標準）
  - https://railsguides.jp/active_job_basics.html
  - Active Jobは、ジョブを宣言し、それによってバックエンドでさまざまな方法によるキュー操作を実行するためのフレームワークです。
  - バックエンド
  - ActiveJobにはキューイングバックエンドに接続できるアダプタが必要となります。以下それぞれのアダプタについて解説いたします。
    - Sidekiq
    - https://github.com/sidekiq/sidekiq
    - キューストレージ：Redis
    - マルチスレッドで動くので処理速度が速く、メモリ効率も高い
  - Resque
    - https://github.com/resque/resque
    - キューストレージ：Redis
    - シングルスレッド・マルチプロセスで動く為、メモリリークなどは起こしづらい
  - Delayed Job
    - https://github.com/collectiveidea/delayed_job
    - キューストレージ：RDBMS
    - ストレージにRDBMSを使用するため、導入が容易
```

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・ユーザー登録時のパスワードの部分が分かりにくかったです。
・良い出来事の投稿を５つ行わなければ画像が変わらないことに、やや面倒を感じました。
・悪い出来事を投稿後、良い出来事を投稿する前のページにおいて、並行口になっている顔文字が何を示しているのかが分からず、このページでは何をすればいいのかが分かりにくかったです。
・トップページの画像部分が、スマホサイズは問題ないですが、それ以上になると引き伸ばされてしまって違和感を感じるものになっていました。
・色の使い方をもう少し工夫した方が統一感が出せるように感じました。
・参考文献：https://book.impress.co.jp/books/1119101155
・独自ドメインにしましょう。
・みんなのイラスト一覧ページが表示しきるまでに、背景が黒色の画面で表示されたり、画像が表示されるまでに時間を要していたので改善したほうが印象が良くなるように思いました。
・みんなのイラスト一覧ページは何をするページなのかが分からなかったです。
・画像生成時にやや時間がかかりすぎているように感じました。上記で共有した機能などを使用してユーザーが待つ時間を非同期処理にするなど工夫を行う必要性を感じました。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by K-Takano41** [comment]
レビューありがとうございます。
頂いた内容をもとにissueを作成しました。
追加したissueは #56 #57 #58 #59 #60 #61 #62 になります。
本リリースは9/30頃を予定しています。

**Comment by Tsuchiya2** [comment]
ご対応ありがとうございます。
引き続き開発頑張ってください。
